# Generated by Django 4.2.11 on 2026-01-10 19:33

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_categoria", models.CharField(max_length=100, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("estado_categoria", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Efectivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "B200Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "B100Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "B50Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "B20Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "B10Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "M5Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "M2Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("M1", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "M0_50Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "M0_20Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "M0_10Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Permisos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_permiso", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("estado_Permiso", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecargaMax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_origen", models.CharField(max_length=20)),
                ("numero_destino", models.CharField(max_length=20)),
                ("saldo_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("monto_carga", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("COMPLETADO", "Completado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_rol", models.CharField(max_length=50, unique=True)),
                ("estado_Rol", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Usuarios",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_usuario", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("fecha_nacimiento", models.DateField()),
                ("telefono", models.CharField(max_length=50, unique=True)),
                (
                    "correo",
                    models.EmailField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("password", models.CharField(max_length=255)),
                ("ci", models.CharField(max_length=20, unique=True)),
                ("ci_departamento", models.CharField(default="EX", max_length=2)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("estado_Usuario", models.BooleanField(default=True)),
                ("imagen_url", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ventas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_venta", models.DateTimeField(auto_now_add=True)),
                ("estado", models.CharField(default="Pendiente", max_length=20)),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.usuarios"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecargaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("cantidad", models.PositiveIntegerField()),
                ("precio_compra", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precio_venta", models.DecimalField(decimal_places=2, max_digits=10)),
                ("estado", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recargas",
                        to="users.categorias",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Productos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_producto", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("precio_compra", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("precio_mayor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock", models.PositiveIntegerField(default=0)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                ("codigo_producto", models.CharField(max_length=50, unique=True)),
                (
                    "imagen_productos",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                ("estado_equipo", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.categorias",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["nombre_producto"],
            },
        ),
        migrations.CreateModel(
            name="DetalleVentaRecarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario_juego_id", models.CharField(max_length=50)),
                ("nombre_jugador", models.CharField(blank=True, max_length=100)),
                ("password_jugador", models.CharField(blank=True, max_length=100)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=10
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=0, editable=False, max_digits=12
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("COMPLETADO", "Completado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                (
                    "recarga",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.recargaproducto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetallesVentas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.PositiveIntegerField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("tipo_venta", models.CharField(max_length=10)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.productos",
                    ),
                ),
                (
                    "venta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.ventas"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UsuariosRoles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.roles"
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.usuarios"
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "rol")},
            },
        ),
        migrations.CreateModel(
            name="RolesPermisos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permiso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.permisos"
                    ),
                ),
                (
                    "rol",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.roles"
                    ),
                ),
            ],
            options={
                "unique_together": {("rol", "permiso")},
            },
        ),
    ]
