# Generated by Django 4.2.11 on 2026-01-08 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DetalleVentaRecarga",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario_juego_id", models.CharField(max_length=50)),
                ("nombre_jugador", models.CharField(blank=True, max_length=100)),
                ("password_jugador", models.CharField(blank=True, max_length=100)),
                ("cantidad", models.PositiveIntegerField(default=1)),
                (
                    "precio",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("COMPLETADO", "Completado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecargaProducto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("estado", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recargas",
                        to="users.categorias",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="detallebillete",
            name="efectivo",
        ),
        migrations.RemoveField(
            model_name="detallemoneda",
            name="efectivo",
        ),
        migrations.AlterUniqueTogether(
            name="efectivodiario",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="efectivodiario",
            name="turno",
        ),
        migrations.RemoveField(
            model_name="efectivodiario",
            name="usuario",
        ),
        migrations.AlterUniqueTogether(
            name="sueldomensual",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="sueldomensual",
            name="usuario",
        ),
        migrations.DeleteModel(
            name="Asistencia",
        ),
        migrations.DeleteModel(
            name="DetalleBillete",
        ),
        migrations.DeleteModel(
            name="DetalleMoneda",
        ),
        migrations.DeleteModel(
            name="EfectivoDiario",
        ),
        migrations.DeleteModel(
            name="SueldoMensual",
        ),
        migrations.DeleteModel(
            name="Turnos",
        ),
        migrations.AddField(
            model_name="detalleventarecarga",
            name="recarga",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="users.recargaproducto"
            ),
        ),
        migrations.AddField(
            model_name="detalleventarecarga",
            name="venta",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detalles_recargas",
                to="users.ventas",
            ),
        ),
    ]
