# Generated by Django 5.1.1 on 2025-04-02 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen_productos',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
