# Generated by Django 4.2.11 on 2026-01-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_detalleventarecarga_recargaproducto_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recargaproducto",
            old_name="precio_unitario",
            new_name="precio_compra",
        ),
        migrations.AddField(
            model_name="recargaproducto",
            name="precio_venta",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
