# Generated by Django 4.2.11 on 2026-01-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_precio_unitario_recargaproducto_precio_compra_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleventarecarga",
            name="precio",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=10
            ),
        ),
        migrations.AlterField(
            model_name="detalleventarecarga",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
        ),
    ]
