# Generated by Django 4.2.11 on 2026-01-08 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_detalleventarecarga_precio_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="detalleventarecarga",
            name="venta",
        ),
    ]
