# Generated by Django 4.2.11 on 2026-01-09 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_remove_detalleventarecarga_venta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Efectivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "B200Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "B100Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "B50Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "B20Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "B10Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "M5Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "M2Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("M1", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                (
                    "M0_50Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "M0_20Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "M0_10Bs",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=12
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="RecargaMax",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_origen", models.CharField(max_length=20)),
                ("numero_destino", models.CharField(max_length=20)),
                ("saldo_total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("monto_carga", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("COMPLETADO", "Completado"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
